name: Commented PR Review Notification
on:
  pull_request_review_comment:
    types: [created]

jobs:
  commented:
    runs-on: ubuntu-latest
    steps:
      - name: Send Comment Message
        uses: Ilshidur/action-discord@0.3.2
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          DISCORD_USERNAME: BFF BOT
          DISCORD_AVATAR: https://github.com/YAPP-Github/24th-App-Team-1-Android/assets/77484719/611fc015-8f91-4645-90c9-2ae9e86d9e7b
          DISCORD_EMBEDS: |
            [
              {
                "title": "새로운 코멘트가 달렸어요 😋😋 \n${{ github.event.pull_request.title }}",
                "color": 4294836188,
                "description": "${{ github.event.comment.html_url }}",
                "fields": [
                  {
                    "name": "Reviewer",
                    "value": "${{ github.event.comment.user.login }}",
                    "inline": true
                  },
                  {
                    "name": "Comment",
                    "value": "${{ github.event.comment.body }}",
                    "inline": true
                  }
                ]
              }
            ]
