name: Opened Issue Notification
on:
  issues:
    types:
      - opened

jobs:
  create-issue:
    name: Discord notification
    runs-on: ubuntu-latest
    steps:
      - name: Send Issue
        uses: Ilshidur/action-discord@0.3.2
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          DISCORD_USERNAME: BFF BOT
          DISCORD_AVATAR: https://github.com/YAPP-Github/24th-App-Team-1-Android/assets/77484719/885117e7-5809-4630-9f37-ede855cdc8c8
          DISCORD_EMBEDS: |
            [
                { 
                  "title": "왔어요 왔어~ 새로운 이슈가 왔어요~🥳\n${{ github.event.issue.title }}",
                  "color": 10478271,
                  "description": "${{ github.event.issue.html_url }}",
                  "fields": [
                    {
                      "name": "Issue Number",
                      "value": "#${{ github.event.issue.number }}",
                      "inline": true
                    },
                    {
                      "name": "Author",
                      "value": "${{ github.event.issue.user.login }}",
                      "inline": true
                    }
                  ]
                }
              ]
